theme: jekyll-theme-minimal
title: fisica y pachucadas
email: selim_gomez@uaeh.edu.mx

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one