# Site settings
title: fisica y pachucadas
email: selim_gomez@uaeh.edu.mx
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: selimibn
github_username:  selimibn

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge

gems: [jekyll-paginate]


# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  notes:
    output: true
    permalink: /notes/:path/
  posts:
    output: true
    permalink: /posts/:path/

