theme: jekyll-theme-minimal
title: fisica y pachucadas
email: selim_gomez@uaeh.edu.mx

markdown: kramdown
mathjax: true

remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - jekyll-remote-theme
 - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
include:
  - about.md

